source 'https://cdn.cocoapods.org/'
use_frameworks!

def commonDependencies
    pod 'RxGesture', :path => '../'
    pod 'RxSwift', '~> 6.0'
end

target 'RxGesture_iOS_Demo' do
    platform :ios, '9.0'
    commonDependencies
end

target 'RxGesture_OSX_Demo' do
    platform :osx, '10.10'
    commonDependencies
end
