source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'RxGesture_iOS_Demo' do
    platform :ios, '8.3'
    pod 'RxGesture', :path => '../'
end

target 'RxGesture_OSX_Demo' do
    platform :osx, '10.10'
    pod 'RxGesture', :path => '../'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0'
            config.build_settings['MACOSX_DEPLOYMENT_TARGET'] = '10.10'
        end
    end
end
